FROM node:16.3.0-alpine
MAINTAINER denis.bosiy@gmail.com
COPY game.js game.js
COPY highscore.js highscore.js
COPY index.html index.html
COPY server.js server.js
COPY style.css style.css
CMD ["node", "server.js"]
EXPOSE 8080